# Generated by Django 4.1.5 on 2023-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCalculator', '0003_composite_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='thermal_conductivity',
            field=models.FloatField(),
        ),
    ]
