# Generated by Django 4.1.5 on 2023-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCalculator', '0004_alter_material_thermal_conductivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(default='grey', max_length=30),
        ),
    ]
